### PR TITLE
Register trung2703.is-an.app

### PR DESCRIPTION
**Pull request by trung6689**
A website for my ondrive index

**Verification Records**

> Type	Name	Value
> `TXT`	`_vercel`	`vc-domain-verify=trung2703.is-an.app,3d86da4fc8d8694db89d`

**Link to Website**
https://onedrive-trung2703.vercel.app

---

- [x] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/cc858fc78fce92d0297bd8fc40d1b71feab7dc3b/README.md?plain=1#L125-L126

**Comment by trung6689** [comment]
I am currently working on a project https://github.com/trung6689/onedrive-vercel-index, and after deploying it to vercel.app, I have the following website and DNS record:

Website: https://onedrive-trung2703.vercel.app/
Type    Name    Value
TXT _vercel        vc-domain-verify=trung2703.is-an.app,3d86da4fc8d8694db89d

**Comment by tarampampam** [comment]
Nope... Take a look here 😉 https://github.com/tarampampam/free-domains/pull/300

**Comment by trung6689** [comment]
@tarampampam ping
tks u

**Comment by tarampampam** [comment]
Did you press the "validate" button?

**Comment by tarampampam** [comment]
ping @trung6689

**Comment by tarampampam** [comment]
Can I remove your domain since you didn't want to validate it?

**Pull request merged**
