### PR TITLE
Medlexo Subdomain

### PR DESCRIPTION
**Pull request by ericbaobao**
### Link to Website

Link: medlexo.is-an.app

### CODE REVIEW

**Comment by ericbaobao** [comment]
@tarampampam the dnscontrol is valid right?

**Comment by tarampampam** [comment]
```
ERROR: in NS medlexo.is-an.app: target (ns1.epizy.com) must end with a (.) 
```

You know what to do :)

**Comment by ericbaobao** [comment]
> ```
> ERROR: in NS medlexo.is-an.app: target (ns1.epizy.com) must end with a (.) 
> ```
> 
> You know what to do :)

@tarampampam cross finger I hope it works~ you are awesome

**Review by tarampampam — APPROVED** [review]

**Comment by ericbaobao** [comment]
@tarampampam it seems like the default NS [is not proxied](https://www.whatsmydns.net/#NS/medlexo.is-an.app) by default right?

**Comment by tarampampam** [comment]
I think yes

**Comment by ericbaobao** [comment]
> I think yes

what should be done to make it proxied by cloudflare?

**Comment by tarampampam** [comment]
Register an account on CF and delegate a subdomain on it :)

**Comment by tarampampam** [comment]
Your nameserver - your settings/rules

**Comment by ericbaobao** [comment]
> Your nameserver - your settings/rules

I can't because it is your cloudflare account, I think you need to login to your clouflare account to do it
image

**Comment by tarampampam** [comment]
Oh my gosh... I believed this is possible. Maybe you know the working scenario?

**Comment by ericbaobao** [comment]
> Oh my gosh... I believed this is possible. Maybe you know the working scenario?

In your Cloudflare dashboard, go to the DNS tab and click the blue “Add Record” button. Then add your Subdomain DNS Record in Cloudflare. I found a screenshot example for `testing.wp-tweaks.com`:
image

**Comment by tarampampam** [comment]
Maybe you can make a new PR by replacing NS with CNAME?

**Comment by ericbaobao** [comment]
> Maybe you can make a new PR by replacing NS with CNAME?

@tarampampam hi again, I just saw your reply, not me change to CNAME, I am using NS.
You need to login to your cloudflare account, then pick NS, I think the above picture is example for reference only since he used CNAME.
image

**Comment by tarampampam** [comment]
Changes in this repo are synced with CF, so if you need to change something - you should do it here (otherwise, any uncommitted changes will be removed on the next deployment).

**Comment by ericbaobao** [comment]
> Changes in this repo are synced with CF, so if you need to change something - you should do it here (otherwise, any uncommitted changes will be removed on the next deployment).

image

is there any misconfiguration? Your readme say it is proxied by default, but it seems like [not proxied in this link
](https://www.whatsmydns.net/#NS/medlexo.is-an.app)

**Comment by tarampampam** [comment]
This is true for `CNAME`, `A`, `AAAA` records, and so on, but not for `NS` (your NS - your rules)

**Comment by tarampampam** [comment]
Technically, NS records delegates zone forwarding on your server

**Comment by ericbaobao** [comment]
> This is true for `CNAME`, `A`, `AAAA` records, and so on, but not for `NS` (your NS - your rules)

ahh I see, is it possible you add a json for NS too? maybe like:
```
{
  ...
  "proxy": false     // disable the CF proxy, proxying is always enabled by default
  "NSproxy": true // enable the CF proxy, proxying is always disabled by default
}
```

**Comment by tarampampam** [comment]
This is not possible, as I told you:

image

**Pull request merged**
