### PR TITLE
Register flier.is-an.app

### PR DESCRIPTION
**Pull request by Lee-Flier**
A website for my vercel app
### Verification Records

Type | Name | Value
-- | -- | --
TXT | _vercel | vc-domain-verify=flier.is-an.app,51e40204daf37f8815a4

### Link to Website

Link: https://chat-gpt-next-web-git-main-lee-flier.vercel.app

- [x] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by SD9735** [comment]
Hall

**Comment by tarampampam** [comment]
done

**Comment by tarampampam** [comment]
Did you verify the domain?

**Comment by Lee-Flier** [comment]
thanks，now can used

**Pull request merged**
