### PR TITLE
Tasknclaim

### PR DESCRIPTION
**Pull request by Techiton**
We Plan to use the domain for our site which lets users earn giftcards, roblox, in-game currency and etc by completing offerwalls and surveys provided by us.

### Link to Website

Link: https://tasknclaim.1bt.uk/
---

- [x] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
Vercel?

**Comment by Techiton** [comment]
> Vercel?

Yes i am using Vercel for hosting the project

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/3f19943fbf95ffa48389e71f1a48185f0bcbf24f/README.md?plain=1#L125-L126

https://github.com/tarampampam/free-domains/issues/97

**Comment by Techiton** [comment]
@tarampampam The validation records that vercel requires
Type - `TXT`
Name - `_vercel`
Value - `vc-domain-verify=tasknclaim.1bt.uk,d25a46a807fc4aeddbbd`

**Comment by tarampampam** [comment]
@Techiton try to check now

**Comment by Techiton** [comment]
> @Techiton try to check now

It worked, thank you

**Pull request merged**
