### PR TITLE
Update azumi.is-an.app.json

### PR DESCRIPTION
**Pull request by AquaQuokka**
Documentation Subdomain

### Link to Website

Link: 

---

https://azumidocs.github.io

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by AquaQuokka** [comment]
Uhhhhhh how do i fix it, something is wrong

**Comment by AquaQuokka** [comment]
@tarampampam What does this error mean?

**Comment by AquaQuokka** [comment]
YOOOOOOOOO IT WORKED

**Comment by AquaQuokka** [comment]
Now we just need to merge

**Comment by AquaQuokka** [comment]
Hey @tarampampam can you add a nested subdomain called "blog.azumi" that points towards "hashnode.network" please? I can't get the darn JSON working :(

**Comment by tarampampam** [comment]
I had slept (yea, sometimes I need to sleep, sorry for that 😁)

**Comment by AquaQuokka** [comment]
Hey, uh something isn't right
image

**Comment by AquaQuokka** [comment]
You know if anything is wrong? @tarampampam

**Comment by AquaQuokka** [comment]
wait nvm it probably just needs time to actually work

**Comment by AquaQuokka** [comment]
Hrmmm neither of the domains are working

**Comment by AquaQuokka** [comment]
image
image

**Comment by AquaQuokka** [comment]
Any idea why, or should I just wait? @tarampampam

**Comment by AquaQuokka** [comment]
wait no wonder the blog one isn't working... you didn't add it :(

**Comment by tarampampam** [comment]
Here we go!

```bash
$ dig +noall +answer azumi.is-an.app
azumi.is-an.app.	300	IN	A	104.21.64.101
azumi.is-an.app.	300	IN	A	172.67.181.22

$ dig +noall +answer docs.azumi.is-an.app
docs.azumi.is-an.app.	300	IN	A	104.21.64.101
docs.azumi.is-an.app.	300	IN	A	172.67.181.22
```

Check it now

**Comment by AquaQuokka** [comment]
image
😔

**Comment by AquaQuokka** [comment]
I'll try restarting my browser

**Comment by tarampampam** [comment]
It may take some time. Could you test from the terminal?

**Comment by AquaQuokka** [comment]
> It may take some time. Could you test from the terminal?

How?

**Comment by AquaQuokka** [comment]
image
Also doesn't work on an uncached browser

**Comment by AquaQuokka** [comment]
> ~It may take some time. Could you test from the terminal?~
> 
> Try to re-register your subdomain

As in removing my CNAME file and re-adding it?

**Comment by tarampampam** [comment]
Is the SSL configured properly?

**Comment by AquaQuokka** [comment]
> Is the SSL configured properly?

I'm using GitHub pages, it should do that itself

**Comment by AquaQuokka** [comment]
right?

**Comment by tarampampam** [comment]
> As in removing my CNAME file and re-adding it?

Nonono. Show me your page with custom domain settings, please

**Comment by tarampampam** [comment]
At this moment:

```
$ curl -v https://docs.azumi.is-an.app
*   Trying 172.67.181.22:443...
* TCP_NODELAY set
* Connected to docs.azumi.is-an.app (172.67.181.22) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

**Comment by AquaQuokka** [comment]
image

**Comment by tarampampam** [comment]
Check "Enforce HTTPS"

**Comment by AquaQuokka** [comment]
Your domain service doesn't support it

**Comment by AquaQuokka** [comment]
image

**Comment by AquaQuokka** [comment]
i'll check my main site

**Comment by AquaQuokka** [comment]
image
Main site doesn't support it either

**Comment by AquaQuokka** [comment]
wait it might be a cloudflare issue

**Comment by AquaQuokka** [comment]
should i add this?
`
{
  "proxy": false
}
`

**Comment by tarampampam** [comment]
All domain records are in the right places:

```shell
$ dig azumi.is-an.app
azumi.is-an.app.	300	IN	A	104.21.64.101
azumi.is-an.app.	300	IN	A	172.67.181.22

$ dig docs.azumi.is-an.app
docs.azumi.is-an.app.	300	IN	A	104.21.64.101
docs.azumi.is-an.app.	300	IN	A	172.67.181.22

$ dig blog.azumi.is-an.app
blog.azumi.is-an.app.	300	IN	A	172.67.181.22
blog.azumi.is-an.app.	300	IN	A	104.21.64.101SIZE  rcvd: 81
```

**Comment by tarampampam** [comment]
> should i add this? `{ "proxy": false }`

I think no

**Comment by AquaQuokka** [comment]
wait wut
you never added blog tho

**Comment by tarampampam** [comment]
> wait it might be a cloudflare issue

Maybe. Try to remove the custom domain, wait a minute and add it back, maybe?

**Comment by AquaQuokka** [comment]
alright without custom domain it works

**Comment by AquaQuokka** [comment]
i'll add it back in a few minutes

**Comment by tarampampam** [comment]
> wait wut you never added blog tho

https://github.com/tarampampam/free-domains/blob/56f358701072d30ff2333d19999e3b0c508abe23/domains/azumi.is-an.app.json#L1-L27

I did. Are these the right records?

**Comment by AquaQuokka** [comment]
yep

**Comment by tarampampam** [comment]
So, let's try to wait

**Comment by AquaQuokka** [comment]
> So, let's try to wait

What is this waiting thing you speak of 😆

**Comment by tarampampam** [comment]
Sorry for those strange troubles

**Comment by AquaQuokka** [comment]
image
Interesting... I added the domain again to my blog after the DNS change, and it worked, but it gives the same error as the other sub-subdomain

**Comment by AquaQuokka** [comment]
hey, considering nothing else is working, let's try the cloudflare proxy thing

**Comment by AquaQuokka** [comment]
if it doesn't work, we can just revert

**Comment by AquaQuokka** [comment]
hey could you re-open this pull @tarampampam

**Comment by tarampampam** [comment]
Just wait for an hour

**Comment by AquaQuokka** [comment]
> @AquaQuokka Here we go!
> 
> ```shell
> $ dig +noall +answer azumi.is-an.app
> azumi.is-an.app.	300	IN	A	104.21.64.101
> azumi.is-an.app.	300	IN	A	172.67.181.22
> 
> $ dig +noall +answer docs.azumi.is-an.app
> docs.azumi.is-an.app.	300	IN	A	104.21.64.101
> docs.azumi.is-an.app.	300	IN	A	172.67.181.22
> ```
> 
> Check it now

As in another hour or like 11 mins

**Comment by AquaQuokka** [comment]
nvm im just impatient lol

**Comment by tarampampam** [comment]
Nope. Create a new, please

**Comment by AquaQuokka** [comment]
ok

**Comment by AquaQuokka** [comment]
alright what changes should i make in my file

**Comment by AquaQuokka** [comment]
wait i think the proxy false will make it work

**Pull request merged**
