### PR TITLE
Update shredmod.is-an.app.json

### PR DESCRIPTION
**Pull request by familycomicsstudios**
I need more space for my packager
---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
Please describe - why you need the exact wildcard subdomain

**Comment by familycomicsstudios** [comment]
I need the full wildcard subdomain so I can add multiple repositories (packager.shredmod, extensions.shredmod, etc)

> Please describe - why you need the exact wildcard subdomain

**Comment by tarampampam** [comment]
I suggest you use nested records, instead of wildcards. Eg:

```json
{
  "record":{
    "CNAME": "shredmod.github.io"
  },
  "nested": [
    {
      "subdomain": "api",
      "record": {
        "CNAME": "shredmod.github.io"
      }
    },
    {
      "subdomain": "assets",
      "record": {
        "CNAME": "shredmod.github.io"
      }
    }
  ]
}
```

I guess you don't have that many subdomains to register, right?

**Comment by tarampampam** [comment]
Why did you reopen this?

**Pull request closed without merging**
