### PR TITLE
Update azumi.is-an.app.json

### PR DESCRIPTION
**Pull request by AquaQuokka**
### Link to Website

Link: 

---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by AquaQuokka** [comment]
@tarampampam New

**Comment by tarampampam** [comment]
`https://azumi.is-an.app/` works fine right now, so, why do you want to disable the proxy for it?

**Comment by AquaQuokka** [comment]
> `https://azumi.is-an.app/` works fine right now, so, why do you want to disable the proxy for it?

oh whoops can you move the property change to the two nested ones instead? idk where to put stuff lol

**Comment by AquaQuokka** [comment]
ty

**Comment by tarampampam** [comment]
Is now ok?

**Comment by AquaQuokka** [comment]
well, you haven't merged it yet, so how will we know?

**Comment by AquaQuokka** [comment]
IT WORKEDDDD

**Comment by AquaQuokka** [comment]
the enforce https bit at least

**Comment by AquaQuokka** [comment]
i need to check the sites

**Comment by AquaQuokka** [comment]
Hey @tarampampam can you disable proxy on the blog subdomain as well?

**Comment by AquaQuokka** [comment]
The docs site works now

**Pull request merged**
