### PR TITLE
Add searxng.is-an.app

### PR DESCRIPTION
**Pull request by iamrony777**
### I am running an instance of SearxNG and would like to list it on the public [SearxNG and Searx instance listing](https://searx.space/). This is for both personal use and to make the instance publicly accessible.

[Link to fork](https://github.com/iamrony777/searxng)

### Link to Website

Link: [SearxNG Instance](https://8080-fb52089fb827495cbc983f0e1aa0ac58.onpatr.cloud/search)

---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
Fix the errors, please

**Comment by iamrony777** [comment]
> Fix the errors, please

Error says TXT and CNAME records can't be used simultaneously. I'm trying to log into patr but there's a server side problem so it will take time

**Comment by tarampampam** [comment]
Why do you need a txt record?

**Comment by iamrony777** [comment]
> Why do you need a txt record?

To verify domain. In patr , we need to add domain first (verification process requires txt records, without verification domain will be removed in 7days). Then create subdomain url from deployment (docker app)

verify

add-url

**Comment by tarampampam** [comment]
Do you know if the TXT record should exist permanently or only for domain verification purposes?

**Comment by iamrony777** [comment]
> Do you know if the TXT record should exist permanently or only for domain verification purposes?

Unfortunately no. I'm closing PR

**Pull request closed without merging**
