### PR TITLE
Create future.is-an.app.js

### PR DESCRIPTION
**Pull request by Huseyin-Cinar**
### Link to Website

Link: 

---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Review by tarampampam — APPROVED** [review]

**Comment by Huseyin-Cinar** [comment]
@tarampampam thank you man!

**Comment by Huseyin-Cinar** [comment]
@tarampampam hey bro when does the domain open?

**Comment by tarampampam** [comment]
As soon as MR was merged:

```bash
$ dig +noall +answer dig future.is-an.app

future.is-an.app.	274	IN	CNAME	futuree.netlify.app.
futuree.netlify.app.	20	IN	A	18.192.231.252
futuree.netlify.app.	20	IN	A	34.141.103.251
```

**Comment by Huseyin-Cinar** [comment]
**Hey, @tarampampam**

Can you delete future.is-an.app.js? I'm going to change the CNAME and upload it again. Or you could just make your CNAME for me github.com/The-Future-Software-Company. Thanks.

**Comment by tarampampam** [comment]
Or you can edit the existing record in a file, right? 😃

**Comment by Huseyin-Cinar** [comment]
> Or you can edit the existing record in a file, right? 😃

i tried but i couldn't

**Comment by Huseyin-Cinar** [comment]
> Or you can edit the existing record in a file, right? 😃

image

It's disabled

**Pull request merged**
