### PR TITLE
Create anonaddy.is-an.app.js

### PR DESCRIPTION
**Pull request by ririko5834**
### Link to Website

Link: 

 
---

- [ x] Toggle this checkbox to re-run the stargazer checking

I want to use the subdomain for selfhosted anonaddy instance https://github.com/anonaddy/anonaddy which I will use for personal usage only, it won't be released to public (registration wont be open), I will make accounts on it only for my friends.

### CODE REVIEW

**Comment by ririko5834** [comment]
Starred it 
image

When will you approve it?

Btw I used .ml domain from freedom before for anonaddy, but all .ml domains stopped working so I am finding an alternative domain to use for my anonaddy instance.

**Comment by ririko5834** [comment]
Why?

**Comment by ririko5834** [comment]
So which subdomain provider supports it

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/489c6bf281afcdba1f97be3f0621f50fbc1da873/domains/service/%40.is-an.app.js#L9-L11
https://github.com/tarampampam/free-domains/blob/489c6bf281afcdba1f97be3f0621f50fbc1da873/domains/service/_dmarc.is-an.app.js#L9-L11
https://github.com/tarampampam/free-domains/blob/489c6bf281afcdba1f97be3f0621f50fbc1da873/domains/service/_domainkey.is-an.app.js#L9-L11

**Comment by ririko5834** [comment]
Why did you add it there?

**Pull request closed without merging**
