### PR TITLE
Update and rename acceleratorow.1bt.uk.js to acceleratorow.is-an.app.js

### PR DESCRIPTION
**Pull request by Accelerator-OW**
### Link to Website

Link: 140.83.81.12

---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
Check the 2nd row in the checklist, please

**Comment by Accelerator-OW** [comment]
Oh sorry, did I do it correctly?

**Comment by tarampampam** [comment]
And could u remove the whole comments, please?

**Comment by tarampampam** [comment]
Please, create a new PR with all the required changes

**Pull request closed without merging**
