### PR TITLE
Remove mass-registered domains

### PR DESCRIPTION
**Pull request by tarampampam**
Domains will be deleted because:

- Profiles in use are newly created
- Similar to each other like two peas in a pod
- Do not respond to the questions asked in PR
- Register domains with the same frequency (very similar to automation)
- Linked to the same company
- None of them are associated with any project on GitHub or elsewhere

Ping for the "owners" - I will keep your domains for one week (so that you have time to migrate them elsewhere). Or explain a reason why should I keep them, please.

@ansari-saify
@kaushik-bhadarka
@sharad-rajyaguru
@pandya-riddhi
@prajapati-divya
@nitesh-rathod
@nayan-gorasiya
@limbanitejal
@viral-gadhiya
@dharti-mungara
@jagdish-der
@shahjenish
@yash-poojara
@darji-ravi
@chintan-prajapati
@chirag-adhvaryu
@ankiprajapati
@jagdish-mer
@surajh-patel
@mandaninikunj
@sanjay-suryavanshi
@keyurnimavat
@pathan-imran
@lakhani-palak
@jay-bhalodiya
@vyas-rahul
@mihir-patel-agc
@heli-joshi
@bhumkah-patel
@verma-sanjeet
@ajay-charotariya
@surendran-soumya
@shoaib-shaikhh
@naman-machchhar
@grishma-chhayani
@patel-hetal
@ajit-thakor
@dudani-meet
@soumyah-das
@shakeel-ahamad
@priti-shide
@akta-chavda
@panchal-chirag
@bipin-bheda
@viren-trivedi
@hiren-brahmbhatt
@pal-rakesh
@ravi-pate
@sweta-solanki
@hitesh-makodiya

### CODE REVIEW

**Comment by tarampampam** [comment]
@patel-jatin
@mahevish-husseni
@mukesh-tadpad
@patel-prathiv
@nirav-bhut
@chirag-parikh
@jay-d-dave
@patel-radhika
@samir-vaghela
@hinal-sanghvi
@ujalakhasiya
@kishan-bagiya
@dinesh-vaghasia
@p-kinjal
@maheta-bhavik
@soni-aakas
@savan-makawana
@singh-jitendar
@sanjay-makasana
@pratike-patel
@mausami-parmar
@dipmala-shrimali
@harshad-patoliya
@patel-darshit
@viplav-mistry
@niki-tiwari
@shweta-gotecha
@mohammedasif-shaikh
@priyas-rana

**Comment by tarampampam** [comment]
If anyone could discuss this - feel free to leave your comments

**Comment by 1986webdeveloper** [comment]
> If anyone could discuss this - feel free to leave your comments

Hey @tarampampam 

This profiles were creaetd for training purpose so developers can then change them, they never did because, our next session is by end of this week, once they have it, they will start modifying, please support them 3 weeks and then if someone does not follow you can remove them.

**Comment by tarampampam** [comment]
@1986webdeveloper I think one week is enough to make all the required changes, so - I'm sorry, but only one week

**Comment by 1986webdeveloper** [comment]
> @1986webdeveloper I think one week is enough to make all the required changes, so - I'm sorry, but only one week

Okay

**Comment by 1986webdeveloper** [comment]
> @1986webdeveloper I think one week is enough to make all the required changes, so - I'm sorry, but only one week

Hey @tarampampam 
We have changed the content of every profile. please look once.

**Comment by 1986webdeveloper** [comment]
Hey @tarampampam 

@patel-jatin @mahevish-husseni @mukesh-tadpad @patel-prathiv @nirav-bhut
@chirag-parikh @Jay-d-dave @patel-radhika @samir-vaghela @hinal-sanghvi @ujalakhasiya
@kishan-bagiya @dinesh-vaghasia @p-kinjal @maheta-bhavik @soni-aakas @savan-makawana
@singh-jitendar @sanjay-makasana @pratike-patel @mausami-parmar @dipmala-shrimali @harshad-patoliya
@Patel-Darshit @viplav-mistry @niki-tiwari
@shweta-gotecha @mohammedasif-shaikh @priyas-rana
@ansari-saify @kaushik-bhadarka @sharad-rajyaguru
@pandya-riddhi @prajapati-divya
@nitesh-rathod @nayan-gorasiya @limbanitejal
@viral-gadhiya @dharti-mungara @jagdish-der
@shahjenish @yash-poojara @darji-ravi @chintan-prajapati @Chirag-Adhvaryu @ankiprajapati
@jagdish-mer @surajh-patel
@mandaninikunj 
@Sanjay-Suryavanshi 
@keyurnimavat  @pathan-imran 
@lakhani-palak @jay-bhalodiya
@vyas-rahul @mihir-patel-agc
@heli-joshi @bhumkah-patel
@verma-sanjeet @ajay-charotariya
@surendran-soumya @shoaib-shaikhh @naman-machchhar
@grishma-chhayani @patel-hetal @ajit-thakor @dudani-meet @soumyah-das
@shakeel-ahamad @priti-shide @akta-chavda
@panchal-chirag @bipin-bheda @viren-trivedi @hiren-brahmbhatt @pal-rakesh @ravi-pate @sweta-solanki @hitesh-makodiya


We have updates all the profiles. please check once and let me know if anychanges are required.

Thank you for the supporting.

**Pull request merged**
