### PR TITLE
TXT updates and Repo link updates for gravity.is-an.app hosted on vercel

### PR DESCRIPTION
**Pull request by HarisETH**
### Link to Website

Link: [usegravitytool.vercel.app](https://usegravitytool.vercel.app)

---

- [x] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
Are you seriously 😒

**Comment by HarisETH** [comment]
Sorry man ! Vercel shows some verification error 🤐

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/9f74506f99b0cc0c6d75784fb402d37baeafbe7e/README.md?plain=1#L122-L123

**Comment by HarisETH** [comment]
image

**Comment by tarampampam** [comment]
Press the "Refresh" button now

**Comment by tarampampam** [comment]
You're welcome! 😺

**Pull request closed without merging**
