### PR TITLE
Added subdomain - gravity

### PR DESCRIPTION
**Pull request by HarisETH**

### CODE REVIEW

**Review by tarampampam — CHANGES_REQUESTED** [review]
Remove the comments, please

**Comment by HarisETH** [comment]
Comments Removed

**Comment by tarampampam** [comment]
> Comments Removed

Nope

**Comment by HarisETH** [comment]
Give it a check now

**Review by tarampampam — APPROVED** [review]

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/9f74506f99b0cc0c6d75784fb402d37baeafbe7e/README.md?plain=1#L122-L123

**Pull request merged**
