### PR TITLE
Update for todolist.is-an.app

### PR DESCRIPTION
**Pull request by Rainy0123**
### Link to Website

Link: https://e13ad4e1-0f2e-49c8-8610-78762eff2487.id.repl.co

---

- [x] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by Rainy0123** [comment]
@tarampampam  Sorry for being dumb, but I found out the reason of my website was down was because I **did not** put the TXT record.
But I don’t understand how the TXT record works.
Maybe you help me?
TXT Record: `replit-verify=e13ad4e1-0f2e-49c8-8610-78762eff2487`

**Comment by Rainy0123** [comment]
> @tarampampam Sorry for being dumb, but I found out the reason of my website was down was because I **did not** put the TXT record.
> But I don’t understand how the TXT record works.
> Maybe you help me?
> TXT Record: `replit-verify=e13ad4e1-0f2e-49c8-8610-78762eff2487`

If there is anything wrong with the TXT Record.

**Comment by tarampampam** [comment]
What's the name of the TXT record? Could you provide a screenshot with the verification steps?

**Comment by tarampampam** [comment]
I should append it manually

**Comment by Rainy0123** [comment]
> I should append it manually

I accidentally close the pull request lol

**Comment by Rainy0123** [comment]
I am gonna rewrite the whole thing.

**Pull request closed without merging**
