### PR TITLE
I need to update NS

### PR DESCRIPTION
**Pull request by masckmaster2007**
### Link to Website

Link: https://dimisaio.x10.mx
**I am trying to update servers this time**

---

- [x] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by masckmaster2007** [comment]
**help**

**Comment by tarampampam** [comment]
Resolve conflicts first, please

**Comment by tarampampam** [comment]
Closed due inactivity

**Comment by masckmaster2007** [comment]
how am i supposed to resolve this

**Pull request closed without merging**
