### PR TITLE
Creating newstorm.is-an.app.js

### PR DESCRIPTION
**Pull request by NewStorm-0**
I will add some small tools in the website for me and my friends to use. It will only spread among me and my friends.
### Link to Website

Link: 
The website can't be accessed unless I have a domain. Because the website server doesn't have a stand-alone ip address
---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
It will not work without a valid SSL on your side. Do you know about that ?

**Comment by NewStorm-0** [comment]
> It will not work without a valid SSL on your side. Do you know about that ?

😭Sorry, I didn't notice it. I will change it to _1bt.uk_ right away.

**Comment by tarampampam** [comment]
1bt will work fine! But maybe you leave .app, but set up a certbot on your server? HTTPS is the de facto standard...

**Comment by NewStorm-0** [comment]
> 

This may take a lot of time. First, I don't have a certificate. Secondly, I don't have access to the command line of the remote server. And I don't find an operation related to _SSL_ in the admin panel😬. My website is meaningless, just for me and my friends to entertain. 😂In my opinion, as long as it works.

**Comment by tarampampam** [comment]
Have fun! 😄

**Pull request merged**
