### PR TITLE
matrix.1bt.uk

### PR DESCRIPTION
**Pull request by maanimis**
### Link to Website

Link: 

---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/6e53da47614a1f2f5a73667a33cec9692d3e2aa7/README.md?plain=1#L34-L35

**Comment by tarampampam** [comment]
When your site will be ready, feel free to open this PR back, ok?

**Comment by maanimis** [comment]
> https://github.com/tarampampam/free-domains/blob/6e53da47614a1f2f5a73667a33cec9692d3e2aa7/README.md?plain=1#L34-L35

so strict :/

**Comment by tarampampam** [comment]
Sorry for that :(

**Pull request closed without merging**
