### PR TITLE
Create whatsme.is-an.app.json

### PR DESCRIPTION
**Pull request by DhruvilMoradiya**
### Link to Website

Link: 
https://whatsme05.web.app

### CODE REVIEW

**Comment by tarampampam** [comment]
Please, check the JSON format here - https://jsonlint.com/

**Review by tarampampam — CHANGES_REQUESTED** [review]
Wrong format

**Comment by DhruvilMoradiya** [comment]
> Wrong format

Is it okay now ?

**Comment by DhruvilMoradiya** [comment]
Close

**Pull request closed without merging**
