### PR TITLE
Add Domain "smp.is-an.app"

### PR DESCRIPTION
**Pull request by YanDao0313**
### Link to Website

Link: https://yandao0313.github.io/SakanaMusicPlayer/ 

Demo Screenshot

Sakana Music Player Desktop Demo

### Usage

Personal project - an online music player by using vanilla javascript.

Just for studying & fun.

### CODE REVIEW

**Comment by tarampampam** [comment]
Please, follow the checklist

**Comment by YanDao0313** [comment]
Hi, I've changed the file. Please check again, thanks.

**Review by tarampampam — APPROVED** [review]

**Review by tarampampam — CHANGES_REQUESTED** [review]
Change the filename, please

**Comment by tarampampam** [comment]
`domains/smp.is-an.app.json` will be better, right? 😊

**Review by tarampampam — APPROVED** [review]

**Comment by YanDao0313** [comment]
Thanks a lot! 😀
[smp.is-an.app](https://smp.is-an.app/)

**Comment by tarampampam** [comment]
You're welcome, buddy! 👍🏼

**Pull request merged**
