### PR TITLE
Update yt2mp3.is-an.app.js

### PR DESCRIPTION
**Pull request by avalynndev**
### Note: I created this PR not to issue a big change, but to notify the owner about adding this TXT record, as i deleted my website by mistake causing the URL to disconnect from the Project

This is a website the converts Youtube links to mp3/mp4 videos

| Type | Name | Value |
| -------- | ------- | ------- |
| TXT | _vercel | vc-domain-verify=aviana.is-an.app,08ef3cdd4263b37d6f65 |

### Link to Website

Link: https://youtube2mp3.vercel.app/

---

- [ ] Toggle this checkbox to re-run the stargazer checking

### CODE REVIEW

**Comment by tarampampam** [comment]
@avalynndev Sorry for the long waiting time. Could you pass the domain verification now?

**Comment by tarampampam** [comment]
ping @avalynndev

**Comment by avalynndev** [comment]
TXT
_vercel
vc-domain-verify=yt2mp3.is-an.app,50d598710fa4a7c7c4d4

**Comment by avalynndev** [comment]
ping @tarampampam

**Comment by tarampampam** [comment]
@avalynndev done

**Comment by avalynndev** [comment]
image

@tarampampam ping

**Comment by tarampampam** [comment]
@avalynndev pong

**Comment by avalynndev** [comment]
whats wrong with it?
@tarampampam

**Pull request merged**
